### ISSUE TITLE
Support "kendo-jquery" in angular 2+ applications

### ISSUE THREAD

**Issue by yasmoradi** [telerik/kendo-angular-jquery-integration#2]
I'm aware of **kendo-angular 2+** applications, but could you please support **kendo-jquery** in angular 2+ apps as like as what you've done for react? We've invested a lot in kendo data source (for example we've integrated that with indexedb) and there are a lot of features which are not available in **kendo-angular 2+**.

Thanks in advance.

**Comment by gyoshev** [comment]
We have published a help topic that shows [how to use Kendo UI for jQuery in Angular 2+ applications](https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/). This will allow you to use the Kendo UI for jQuery Grid and DataSource in an Angular 2 application.

At this time it is not planned to have the DataSource component ported to the Angular Grid component, as data operations are handled by the [kendo-data-query package](https://www.telerik.com/kendo-angular-ui/components/dataquery/), combined with data fetching mechanisms specific for the Angular framework. This gives you much more control over the application, and adheres to the Angular framework design.
