### ISSUE TITLE
Support Granular import for angular 2+ applications

### ISSUE THREAD

**Issue by PSchicht** [telerik/kendo-angular-jquery-integration#4]
Hey,

I'm working on a angular 5 application with Kendo UI Angular. Since no editor component is available at this point in time, I followed the angular jquery integration example and created a component to wrap the editor.

But since the import of the jquery kendo is only possible with this:  

``` 
import '@progress/kendo-ui/';
``` 

it imports the whole package and the vendor.bundle will grow by 9MB. Can you please explain how to import only the editor?

Thx a lot!
Pascal

**Comment by svetq** [comment]
@PSchicht  ,

Importing just the editor can be achieved in the following way:

`import '@progress/kendo-ui/js/kendo.editor';`
