### ISSUE TITLE
Add Scheduler component to Material theme

### ISSUE THREAD

**Issue by kdubious** [telerik/kendo-angular-jquery-integration#5]
The scheduler fails with the Material theme.

I think I've tried all variations of the following:

    //@import "node_modules/@progress/kendo-theme-default/scss/all";
    @import 'node_modules/@progress/kendo-ui/css/web/kendo.common.css';
    @import 'node_modules/@progress/kendo-ui/css/web/kendo.default.css';
    //@import 'node_modules/@progress/kendo-ui/css/web/kendo.material.css';
    @import 'node_modules/@progress/kendo-theme-material/scss/all';

**Comment by gyoshev** [comment]
`@progress/kendo-theme-material` is designed to be self-contained and is not compatible with the theme files shipped in `@progress/kendo-ui`.

Alas, the Scheduler component is not available in the `@progress/kendo-theme-material` package at this time. A possible workaround is to use the Scheduler styles from `@progress/kendo-theme-default`, with the variables from `kendo-theme-material`, like this:

```scss
@import 'node_modules/@progress/kendo-theme-material/scss/all';
@import 'node_modules/@progress/kendo-theme-default/scss/scheduler';
```

The above approach is not supported officially, but it might yield useful results. Once the Scheduler component is shipped in `@progress/kendo-theme-material`, the import from the Default theme will be ignored automatically.

**Comment by gyoshev** [comment]
The Material theme includes Scheduler styles since version `1.3.0`, so I'm closing this issue.
